# Generated by Django 4.0.1 on 2022-01-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['libele'],
            },
        ),
        migrations.CreateModel(
            name='Godfather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='godfather')),
                ('preferences', models.ManyToManyField(to='sponsorship.Preferences')),
            ],
        ),
        migrations.CreateModel(
            name='Goddaughter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='goddaughter')),
                ('preferences', models.ManyToManyField(to='sponsorship.Preferences')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goddaughter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.goddaughter')),
                ('godfather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorship.godfather')),
            ],
        ),
    ]
