# Generated by Django 4.0.1 on 2022-01-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goddaughter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/goddaughter'),
        ),
        migrations.AlterField(
            model_name='godfather',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/godfather'),
        ),
    ]
